-- Create sessions table
create table sessions (
  session_id uuid primary key default gen_random_uuid(),
  user_id text not null,
  start_time timestamp with time zone default now(),
  end_time timestamp with time zone,
  summary text
);

-- Create session_events table
create table session_events (
  id bigint generated by default as identity primary key,
  session_id uuid references sessions(session_id) on delete cascade not null,
  event_type text not null, -- 'user_message', 'ai_message', 'tool_call', 'tool_result'
  content text,
  metadata jsonb, -- store extra details like tokens, headers if needed
  created_at timestamp with time zone default now()
);

-- Enable RLS (Optional but good practice, though we are using server-side client)
alter table sessions enable row level security;
alter table session_events enable row level security;
